{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% set active_menu = 'system' %}
{% block meta_title %}{% trans 'Imgur configuration' %}{% endblock %}

{% block breadcrumbs %}
    <ul>
        <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
        <li><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
        <li class="lastB">{% trans 'Imgur configuration' %}</li>
    </ul>
{% endblock %}


{% block content %}

    <div class="widget">
        <div class="head">
            <h5>{% trans 'Imgur API' %}</h5>
        </div>
        
        {% set params = admin.imgur_config_get %}
        <form method="post" action="{{ 'api/admin/imgur/config_update'|link }}" class="mainForm save api-form" data-api-msg="{% trans 'Configuration updated' %}">
            <div class="help">
                <ol style="list-style: decimal; margin-left: 20px;">
                    <li>{% trans 'Register an Application at' %}: <a href="https://api.imgur.com/oauth2/addclient" target="_blank">https://api.imgur.com/oauth2/addclient</a></li>
                    <li>{% trans 'Select Authorization type:' %} <strong>{% trans 'Anonymous usage without user authorization' %}</strong></li>
                    <li>{% trans 'Authorization callback URL is your Boxbilling base url' %}</li>
                    <li>{% trans 'Please copy and paste Client ID and Secret into field below and click' %} <strong>{% trans 'Update' %}</strong></li>
                </ol>
            </div>
            <fieldset>
                <div class="rowElem noborder">
                    <label>{% trans 'Client ID' %}:</label>
                    <div class="formRight">
                        <input type="text" name="client_id" value="{{params.client_id}}" required="required">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Client secret' %}:</label>
                    <div class="formRight">
                        <input type="text" name="secret" value="{{params.secret}}">
                    </div>
                    <div class="fix"></div>
                </div>

                <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
            </fieldset>
        </form>

        <hr/>
        <div class="help">
            <h3>{% trans 'Add attachment form to template' %}</h3>
            <p>You need to edit admin area and clients support ticket templates <strong>(mod_support_ticket.phtml)</strong> to include attachment upload form</p>
            <p>Add: </p>

            <div class="widget">
                <div class="head"></div>
                <pre class="showCodeJS">
                    {% raw %}{% include 'mod_imgur_upload.phtml with {'support_ticket_id' : ticket.id}'%}{% endraw %}
                </pre>
            </div>

            <p>{% trans 'Admin area template file should be at' %}: <strong>bb-themes/admin_default/html</strong></p>
            <p>{% trans 'Client area template file should be at' %}: <strong>bb-themes/huraga/html</strong> {% trans 'or' %} <strong>src/bb-modules/support/client_html</strong></p>

        </div>

    </div>
        
{% endblock %}