{% set imageUrl = client.imgur_imageExists({'support_ticket_id' : support_ticket_id}) %}
<form method="post" action="{{ 'api/client/imgur/uploadImage'|link }}" class="mainForm" enctype="multipart/form-data"
      target="uploadframe" id="imgur-upload-form">
    <fieldset>

        <div class="rowElem">
            <div class="formRight noborder">
                <input type="file" name="image" id="image">
                <input type="hidden" name="support_ticket_id" value="{{support_ticket_id}}" />
            </div>
            <div class="fix"></div>
        </div>

        <input type="submit" value="Upload" class="btn btn-small submitForm" id="bb-upload-button"/>
    </fieldset>

    {% if imageUrl %}
        <a class="btn btn-small" href="{{ imageUrl }}" target="_blank">{% trans 'View' %}</a>
    {% endif %}
</form>

<script type="text/javascript">
    $(function () {
        $('body').append('<iframe id="uploadframe" name="uploadframe" style="display:none" />');
        $('#imgur-upload-form').submit(function () {
            $(this).attr('action', bb.restUrl('client/imgur/uploadImage'));
            iframe = $('#uploadframe').load(function () {
                response = iframe.contents().find('body');
                data = $.parseJSON(response.text());
                if (data.error) {
                    bb.error(data.error.message, data.error.code);
                }
                if (data.result) {
                    bb.msg('File was uploaded');
                }
                setTimeout(function () {
                    response.html('');
                }, 1);
            });
        });
    });
</script>